# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPy2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_py2(self):
        # Test name: py 2
        # Step # | name | target | value
        # 1 | open | /statements |
        self.driver.get("http://localhost:9999/statements")
        # 2 | setWindowSize | 1292x766 |
        self.driver.set_window_size(1292, 766)
        # 3 | click | id=search_account_id |
        self.driver.find_element(By.ID, "search_account_id").click()
        # 4 | type | id=search_account_id | 10
        self.driver.find_element(By.ID, "search_account_id").send_keys("4")
        # 5 | sendKeys | id=search_account_id | ${KEY_ENTER}
        self.driver.find_element(By.ID, "search_account_id").send_keys(Keys.ENTER)
        # 6 | click | css=.btn |
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        # 7 | click | css=#from_datepicker > .input-group-addon |
        self.driver.find_element(By.CSS_SELECTOR, "#from_datepicker > .input-group-addon").click()
        # 8 | click | css=tr:nth-child(1) > .day:nth-child(5) |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .day:nth-child(5)").click()
        # 9 | click | name=from_date |
        self.driver.find_element(By.NAME, "from_date").click()
        # 10 | click | css=.input-group-addon:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".input-group-addon:nth-child(2)").click()
        # 11 | click | css=tr:nth-child(5) > .day:nth-child(6) |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
        # 12 | click | name=to_date |
        self.driver.find_element(By.NAME, "to_date").click()
        # 13 | click | name=to_date |
        self.driver.find_element(By.NAME, "to_date").click()
        # 14 | doubleClick | name=to_date |
        element = self.driver.find_element(By.NAME, "to_date")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 15 | click | css=.btn |
        self.driver.find_element(By.CSS_SELECTOR, "button.btn.btn-primary").click()
        # 16 | click | css=html |
        self.driver.find_element(By.CSS_SELECTOR, "html").click()
        # 17 | click | css=html |
        self.driver.find_element(By.CSS_SELECTOR, "html").click()

obj = TestPy2()
obj.setup_method('')
obj.test_py2()
#obj.teardown_method('')
