# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestPuy():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        # print('setup completed ')

    def teardown_method(self, method):
        self.driver.quit()

    def test_puy(self):
        # print('starting test ')
        self.driver.get("http://localhost:9999/statements")
        self.driver.set_window_size(1292, 766)
        self.driver.find_element(By.ID, "search_account_id").click()
        self.driver.find_element(By.ID, "search_account_id").send_keys("2")
        self.driver.find_element(By.ID, "search_account_id").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "search_account_id").click()
        self.driver.find_element(By.ID, "search_account_id").send_keys("20")
        self.driver.find_element(By.ID, "search_account_id").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "#from_datepicker .glyphicon").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .day:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".input-group-addon:nth-child(2) > .glyphicon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".today").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.NAME, "from_date").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(1)").click()
        self.driver.find_element(By.ID, "search_account_id").click()
        self.driver.find_element(By.ID, "search_account_id").send_keys("200")
        self.driver.find_element(By.ID, "search_account_id").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "html").click()


obj = TestPuy()
obj.setup_method('')
obj.test_puy()
# obj.teardown_method('')
